### ISSUE TITLE
Make Craft ID Password Settings Field type=password

### ISSUE THREAD

**Issue by ryanmasuga** [putyourlightson/craft-plugin-sales#1]
### Is your feature request related to a problem? Please describe.
When adding my Craft ID Password to the plugin settings in the CP, it's shown in plain text. 

### Describe the solution you would like
Would be nice if the password field was type="password" - maybe there is a good reason it isn't, but if it's all the same, a password field as type password seems to make sense.

### Additional context
As it stands now, it's a regular text field. I don't know how this is stored in the DB, but having the password field display as plain text _feels_ insecure. 

**Current**
![sales_pass_nothidden](https://user-images.githubusercontent.com/988995/97441882-95918080-18ff-11eb-96cf-be9d35729540.png)

**After Proposed Change**
![sales_password_pass](https://user-images.githubusercontent.com/988995/97441921-a17d4280-18ff-11eb-81f0-88e3fb85f4f4.png)

**Comment by bencroker** [comment]
The `Craft ID Password` field is an environment variable aware autosuggest field. These are always plaintext in Craft (see the SMTP password field in email settings, for example). This is the recommended way of using it:

![Screenshot 2020-10-28 at 14 36 37](https://user-images.githubusercontent.com/57572400/97443378-3c3f4680-192b-11eb-80b0-48653ecd2e04.png)

**Comment by ryanmasuga** [comment]
Got it - thanks for the explanation!
