### ISSUE TITLE
Call for Colours

### ISSUE THREAD

**Issue by bencroker** [putyourlightson/craft-plugin-sales#2]
I'm considering switching out the default colour palette, which currently uses [ApexChart's Palette 1](https://apexcharts.com/docs/themes/) for the first 5 colours plus another 2, for a total of 7 default colours.

![Screenshot 2022-05-21 at 20 05 17](https://user-images.githubusercontent.com/57572400/169663981-046ac675-e016-4434-847c-4df575ba6985.png)

It should be a  "qualitative" colour palette (designed to provide visual differentiation between data points) and contain a least 10 colours. 

This colour palette, from [SAP Fiori](https://experience.sap.com/fiori-design-web/color-palettes/#qualitative-color-palette) of all places, is a candidate.
![Screenshot 2022-05-21 at 20 13 09](https://user-images.githubusercontent.com/57572400/169664221-7c882e75-a3f7-47ff-84c6-6761a542829e.png)

If anyone would like to suggest a colour palette, or even submit their own, then please feel free to contribute ideas here.

**Comment by lindseydiloreto** [comment]
I love it, those colors look beautiful and smooth! ❤️ 

I'm just now learning what a "qualitative" palette is... This is definitely on the right track, and I'd be totally fine with that SAP color scheme. I appreciate that they (sort of) alternate between warm and cool colors, to make the visual distinction a little clearer.

**Comment by engram-design** [comment]
Works for me! Also today I learnt a little more on colour theory 😃

**Comment by bencroker** [comment]
I'm not that fond of it in practice, I think I prefer the current colours which are brighter and more vivid, especially since the first 4 are used in the Monthly Sales chart and the first 2 are used in the Licenses vs Renewals charts. 

![Screenshot 2022-05-22 at 19 49 01](https://user-images.githubusercontent.com/57572400/169708735-7f662dfd-80fa-4d1e-b191-c780aee59cbf.png)

![Screenshot 2022-05-22 at 19 49 34](https://user-images.githubusercontent.com/57572400/169708740-5807e57a-6dc9-4b9c-b696-d941d7e8aec9.png)

![Screenshot 2022-05-22 at 19 52 01](https://user-images.githubusercontent.com/57572400/169708877-3935c74a-8bea-41fb-9cdc-9d6a5a21e91f.png)

**Comment by bencroker** [comment]
I've settled on the following. 10 hand-picked colours from the Tailwind 3 colour scheme that make up a qualitative palette.

![Screenshot 2022-05-22 at 21 06 24](https://user-images.githubusercontent.com/57572400/169711722-583b84b8-8687-47e3-a1aa-0481f1b72fd7.png)

**Comment by bencroker** [comment]
Released in 2.1.0. Ironically, the change is so subtle that you'll hardly notice it. At least we now have 10 standardised colours and the ability to increase the number of colours using the new [config setting](https://github.com/putyourlightson/craft-plugin-sales/blob/478ff83f3b8f93d76bf5c8e625ebff3d61fb17f6/src/config.php#L29).

**Comment by bencroker** [comment]
Note to self to check out the new Adobe Spectrum colour palette if I ever decide to do this again...
https://spectrum.adobe.com/page/color-palette/
https://spectrum.adobe.com/page/color-for-data-visualization/#Categorical
