### ISSUE TITLE
Charts - Separate plugin colors from group metric colors

### ISSUE THREAD

**Issue by lindseydiloreto** [putyourlightson/craft-plugin-sales#3]
Loosely related to #2...

It would be great if we could control the plugin colors _separately_ from the other various metrics. As it currently stands, our custom color palette is applied to **all** of the charts on the page... this can make for some ugly charts if you want to customize just your plugin colors.

To be clear, we can split everything into two groups:
 - Charts which show individual plugins.
 - Charts which lump all plugins together.

Only the "Plugin Sales" chart and one pie chart fall into the first group... Everything else falls into the second group.

Is it possible to separate the colors which represent individual plugins?

**Comment by lindseydiloreto** [comment]
To be honest, I'd even be fine with the group metrics colors being hard-coded. As long as the group metric charts are using a reasonable color scheme, it wouldn't bother me if those colors were non-customizable.

Thanks for considering this FR! 🙏

**Comment by bencroker** [comment]
I'm tempted to say that you should simply choose the first 4 (and especially the first 2) colours carefully. I don't see much need to add new settings and I don't like the idea of hard-coding in colours, as they could clash with the custom colour selection.

**Comment by lindseydiloreto** [comment]
Well... "picking the first 4 carefully" is pretty much what we have now. And it's tricky enough to compile a good color scheme (as you're experiencing with #2), even more so if the first 4 colors are untouchable.

The end result amounts to "never change the first 4 colors". Which leaves us in a tough spot to add complimentary colors... which was the exact end result of #2.

**Comment by bencroker** [comment]
The colour palette setting was intended mainly for adding extra colours with the extra benefit of being able to customise them somewhat, but _not_ for colour-coding plugins. I've provided a pretty and functional colour palette out of the box, which is where I prefer to put my effort currently. I'm open to revisiting this again in future.

**Comment by lindseydiloreto** [comment]
Bummer, though I understand that you have a tiny user base. I'll hold out hope that one day it happens (or maybe I have enough time to submit a PR).

In the meantime, it looks like your new color palette per #2 should help a lot. Now that it goes up to 10 colors, I can probably just ditch my custom color scheme and go back to using the defaults.

Thanks Ben. 👍

**Comment by bencroker** [comment]
It can go beyond 10, using the config setting. https://github.com/putyourlightson/craft-plugin-sales/blob/478ff83f3b8f93d76bf5c8e625ebff3d61fb17f6/src/config.php#L29
